### ISSUE TITLE
Webpack build error IAjaxAdapter

### ISSUE THREAD

**Issue by thinkh** [phovea/phovea_core#17]
When building a phovea application using src/ajax I get the following error:

```
ERROR in [default] D:\dev\repos\phovea\ueber_context\phovea_bootstrap_fontawesome\src\ajax_adapter_jquery.ts:5:8
Module '"D:/dev/repos/phovea/ueber_context/phovea_core/src/ajax"' has no exported member 'IAjaxAdapter'.

ERROR in [default] D:\dev\repos\phovea\ueber_context\phovea_d3\src\ajax_adapter_d3.ts:4:8
Module '"D:/dev/repos/phovea/ueber_context/phovea_core/src/ajax"' has no exported member 'IAjaxAdapter'.
```

**Comment by sgratzl** [comment]
already fixed in https://github.com/phovea/phovea_bootstrap_fontawesome/pull/8

**Comment by thinkh** [comment]
I checked out the [feature_7_buildInfo branch](https://github.com/phovea/phovea_bootstrap_fontawesome/tree/feature_7_buildInfo) and still get the following error: 

```
ERROR in [default] D:\dev\repos\phovea\ueber_context\phovea_d3\src\ajax_adapter_d3.ts:4:8
Module '"D:/dev/repos/phovea/ueber_context/phovea_core/src/ajax"' has no exported member 'IAjaxAdapter'.
```

According to the d3 repo the import is still there: https://github.com/phovea/phovea_d3/blob/master/src/ajax_adapter_d3.ts#L10

@sgratzl Can I remove the interface from the ajax_adapter_d3?

**Comment by sgratzl** [comment]
I forgot to file an pull request: https://github.com/phovea/phovea_d3/pull/6

**Comment by thinkh** [comment]
Resolved by merging https://github.com/phovea/phovea_d3/pull/6, https://github.com/phovea/phovea_bootstrap_fontawesome/pull/8, and https://github.com/phovea/generator-phovea/pull/33.
